#!/bin/bash
commit_msg_file=$1

if ! grep -qE "^(feat|fix|docs|style|refactor|test|chore): .+" "$commit_msg_file"; then
  echo "Erreur: Le message de commit doit suivre la convention des commits conventionnels (e.g., feat: ajout de la fonctionnalité)."
  exit 1
fi
